version: "3"
services:
    frontend:
        container_name: frontend
        build:
            context: ./client
            dockerfile: Dockerfile
        image: carlosep/frontend
        ports:
            - "3000:3000"
        volumes:
            - ./client:/usr/src/app
    backend:
        container_name: backend
        build:
            context: ./server
            dockerfile: Dockerfile
        image: carlosep/backend
        ports:
            - "5000:5000"
        volumes:
            - ./server:/usr/src/app
        links:
            - database
    database:
        image: mariadb:latest
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: {{DB_NAME}}
            MYSQL_USER: {{DB_USER}}
            MYSQL_PASSWORD: {{DB_PASSWORD}}
            MYSQL_ROOT_PASSWORD: {{ROOT_PASSWORD}}
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
        links:
            - "database:db"
